### ISSUE TITLE
It doesn't work on JAVA 1.8 with spring boot 2.3.5

### ISSUE THREAD

**Issue by cronosnn** [oridool/liquibase-locking#4]
Hello there!
I use following:
Java: 1.8.0_202
spring-boot:  2.3.5.RELEASE
liquibase-core: 4.8.0
liquibase-locking: 1.0.0

And I have following error: 
```
2022-05-26 10:56:57.92 [INFO]  "main"  [liquibase.servicelocator#log] -
                        Cannot load service: liquibase/lockservice/ext/LockDatabaseChangeLogGeneratorExt has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2022-05-26 10:56:57.270 [INFO]  "main"  [liquibase.database#log] -
                        Set default schema name to public
2022-05-26 10:56:57.297 [INFO]  "main"  [liquibase.servicelocator#log] -
                        Cannot load service: liquibase/lockservice/ext/LockServiceExt has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2022-05-26 10:56:57.517 [INFO]  "main"  [liquibase.lockservice#log] -
                        Waiting for changelog lock....
2022-05-26 10:57:07.561 [INFO]  "main"  [liquibase.lockservice#log] -
                        Waiting for changelog lock....
2022-05-26 10:57:17.592 [INFO]  "main"  [liquibase.lockservice#log] -
                        Waiting for changelog lock....
2022-05-26 10:57:27.608 [INFO]  "main"  [liquibase.lockservice#log] -
                        Waiting for changelog lock....
2022-05-26 10:57:37.655 [INFO]  "main"  [liquibase.lockservice#log] -
...
2022-05-26 11:01:48.376 [INFO]  "main"  [liquibase.lockservice#log] -
                        Waiting for changelog lock....
2022-05-26 11:01:58.482 [WARN]  "main"  [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext#refresh] -
                        Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by Stanislav Okunev since 5/25/22 12:37 PM
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-05-26 11:02:00.875 [ERROR] "main"  [org.springframework.boot.SpringApplication#reportFailure] -
                        Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by atp-logcollector-5fc8c7455-mrmr5 (10.128.31.36) since 5/25/22 12:37 PM
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:311)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.netcracker.atp.logcollector.Main.main(Main.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:64)
Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by atp-logcollector-5fc8c7455-mrmr5 (10.128.31.36) since 5/25/22 12:37 PM
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:270)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:214)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2405)
	at liquibase.Liquibase.update(Liquibase.java:211)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:314)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
	... 24 common frames omitted

```

if no LOCK then I see message and application starts fine:
```
2022-05-26 14:52:21.497 [INFO]  "main"  [liquibase.servicelocator#log] -
                        Cannot load service: liquibase/lockservice/ext/LockDatabaseChangeLogGeneratorExt has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2022-05-26 14:52:21.736 [INFO]  "main"  [liquibase.database#log] -
                        Set default schema name to public
2022-05-26 14:52:21.770 [INFO]  "main"  [liquibase.servicelocator#log] -
                        Cannot load service: liquibase/lockservice/ext/LockServiceExt has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2022-05-26 14:52:22.323 [INFO]  "main"  [liquibase.lockservice#log] -
                        Successfully acquired change log lock
2022-05-26 14:52:24.275 [INFO]  "main"  [liquibase.changelog#log] -
                        Reading from public.databasechangelog
2022-05-26 14:52:24.961 [INFO]  "main"  [liquibase.lockservice#log] -
                        Successfully released change log lock
```

Could you please help with that...
Thanks

**Comment by oridool** [comment]
Hi @cronosnn ,
According to what you wrote, you downloaded the jar from the release page. 
This jar was built with Java 11. If you take a look in the build.gradle file, you see:
`targetCompatibility = JavaVersion.VERSION_11`

The easiest thing for you to do is simply clone the project and build it yourself with source/target set to 1_8 in the build.gradle file.
If that proves to be working for you, I might change it also in the main branch. 
Thanks.
